name: Build Android SIP Gateway
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix Invalid Java Home
        run: |
          # Удаляем локальные настройки автора, которые ломают нам путь к Java
          rm -f gradle.properties
          # Создаем чистый файл настроек
          echo "org.gradle.jvmargs=-Xmx2048m" > gradle.properties
          # Принудительно очищаем переменную, если она тянет мусор
          unset JAVA_HOME
          export JAVA_HOME=$JAVA_HOME_17_X64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SIP-Gateway-Debug
          path: app/build/outputs/apk/debug/*.apk
