name: Build Android SIP Gateway
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix and Clean Build
        run: |
          # Удаляем старые настройки
          rm -f gradle.properties
          # Создаем новые настройки, чтобы сборка не падала из-за нехватки памяти
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" > gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          chmod +x gradlew

      - name: Build Debug APK
        # Добавляем флаг --stacktrace, чтобы если упадет, мы видели точную причину
        # И флаг --refresh-dependencies, чтобы перекачать битые файлы
        run: ./gradlew assembleDebug --stacktrace --refresh-dependencies

      - name: Upload APK
        if: always() # Загрузить даже если билд упадет наполовину, вдруг файл успел создаться
        uses: actions/upload-artifact@v4
        with:
          name: SIP-Gateway-Debug
          path: app/build/outputs/apk/debug/*.apk
